### PR TITLE
Fix input and output buffers before using as p/invoke parameters

### PR DESCRIPTION
**Pull request by ohopton**
Stops the garbage collector moving them around, so fixes intermittent !secp256k1_fe_is_zero(&ge->x) failures in native library.

### CODE REVIEW

**Comment by zone117x** [comment]
Great work, thank you!

**Comment by ohopton** [comment]
No problem, thanks for the library, yours is by far the fastest Secp256k1
lib for .NET that we've found, orders of magnitude faster than the awful
bouncycastle implementation.

We also use your HoshoEthUtil package, any reason you've unlisted it?

You guys do contract audits and penetration testing for dapps? Might be
worth us having a chat.

**Comment by zone117x** [comment]
We've merged HoshoEthUtil into the core lib of another project that we have yet to publicly release. I'll re-list the original package for you in the mean time.

FunFair looks like a fantastic use of ethereum. We'd love to get in contact, can you email me: mlittle (at) hosho.io ?

**Comment by zone117x** [comment]
@ohopton Would you be interesting in giving feedback on a .NET based solidity development and testing suite that we are developing? We are still working on documentation and expanding the project test coverage before open sourcing. 

It includes design/compile time C# codegen for solidity contracts, a MSTest or xunit contract testing framework, solidity code coverage reports, solidity debugging in VSCode and Visual Studio, a .NET ethereum VM and RPC test server. All built from scratch. 

It looks like our tooling is a perfect match for the stack you use at FunFair (.NET & solidity ?) and we'd love to get your feedback.

**Comment by ohopton** [comment]
Matt,

That sounds great, I’d love to take a look. I’ll drop you an email
tomorrow, alternatively you can find me at oliver at funfair dot io.

Thanks,
Oliver.

**Pull request merged**
